# Generated by Django 5.1 on 2025-09-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0002_otpverification_user_free_account_user_free_plan_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='free_account',
        ),
    ]
