# Generated by Django 5.1 on 2025-09-30 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12)),
                ('expense_id', models.CharField(max_length=12, unique=True)),
                ('expense_name', models.CharField(max_length=255)),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_quantity', models.IntegerField()),
                ('expense_unit', models.CharField(max_length=50)),
                ('expense_category', models.CharField(choices=[('raw_material', 'Raw Material'), ('packaging', 'Packaging'), ('transport', 'Transport'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('expense_bill', models.FileField(blank=True, null=True, upload_to='expense_bills/')),
                ('extra_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
