# Generated by Django 5.1 on 2025-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
